version: '3'
services:
  cinema_project:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000" # host:container
    depends_on:
      - cinema_data
  cinema_data:
    image: 'postgres:14'
    environment:
      POSTGRES_DB: cinema_project_db
      POSTGRES_USER: cinema_project_db_user
      POSTGRES_PASSWORD: 1234
    volumes:
      - 'data:/var/lib/postgresql/data'
volumes:
  data: